title: Hello, world! I'm Hao Truong
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hao Truong # add your name
author-img: my-picture.jpg # add your photo
about-author: I am a PHP, Nodejs, React web developer focusing on Back End development. Always hungry to keep learning. # add description
social-twitter: @haocongnghe # add your Twitter handle
social-facebook: https://www.facebook.com/haotruongvan # add your Facebook handle
social-github: haocongnghe # add your Github handle
social-linkedin: https://www.linkedin.com/in/hao-truong-64357288/# add your Linkedin handle
social-email: haocongnghe@gmail.com# add your Email address

# Disqus
discus-identifier: haotruong # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
